<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_ThuKy</name>
   <tag></tag>
   <elementGuidId>813c9f82-eaba-41d3-9fcb-e5211d25db07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='kt_body']/ngb-modal-window[2]/div/div/app-edit-menu-role-modal/div/div[2]/form/div/div/p-multiselect/div/div[4]/div[2]/ul/p-multiselectitem[2]/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.p-multiselect-item.p-ripple.p-highlight</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>dfd258f7-7f1a-46c4-85a8-789cbd462b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-multiselect-item p-ripple p-highlight</value>
      <webElementGuid>eb87c82b-4e0e-4132-849e-5f10c5d87b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>ThuKy</value>
      <webElementGuid>2283f816-46ea-4941-935f-13c014d0b403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>010a9266-9db0-47ed-9dc9-85985536d7ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ThuKy</value>
      <webElementGuid>266e3c17-22ba-4f8d-afba-eea019b62d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_body&quot;)/ngb-modal-window[@class=&quot;d-block modal fade show&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/app-edit-menu-role-modal[1]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;overlay overlay-block cursor-default modal-body&quot;]/form[@class=&quot;form form-label-right ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-lg-9&quot;]/p-multiselect[@class=&quot;ng-tns-c531-1 ng-touched is-valid p-inputwrapper-filled ng-dirty ng-valid&quot;]/div[@class=&quot;ng-tns-c531-1 p-multiselect p-component p-multiselect-open&quot;]/div[@class=&quot;ng-trigger ng-trigger-overlayAnimation ng-tns-c531-1 p-multiselect-panel p-component ng-star-inserted&quot;]/div[@class=&quot;p-multiselect-items-wrapper ng-tns-c531-1&quot;]/ul[@class=&quot;p-multiselect-items p-component ng-tns-c531-1&quot;]/p-multiselectitem[@class=&quot;ng-tns-c531-1 ng-star-inserted&quot;]/li[@class=&quot;p-multiselect-item p-ripple p-highlight&quot;]</value>
      <webElementGuid>04b9b604-4192-468d-876d-376a2a672a2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='kt_body']/ngb-modal-window[2]/div/div/app-edit-menu-role-modal/div/div[2]/form/div/div/p-multiselect/div/div[4]/div[2]/ul/p-multiselectitem[2]/li</value>
      <webElementGuid>f74289dc-3c08-4d57-b9a9-25edece8a9c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nhóm widget không được xóa để test'])[2]/following::li[1]</value>
      <webElementGuid>b6b0bc50-d88d-4816-9993-96c37482b21c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ThuKy'])[2]/following::li[2]</value>
      <webElementGuid>537cc0f1-3629-4447-95c3-3a343a6760a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LanhDao'])[2]/preceding::li[1]</value>
      <webElementGuid>cb2cbf04-d24d-4467-9518-9a847cd32421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-multiselectitem[2]/li</value>
      <webElementGuid>31199ba5-34b8-4cab-8c02-97912e6a739c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'ThuKy' or . = 'ThuKy')]</value>
      <webElementGuid>a44b2e3e-924e-4736-9877-b72a4748289d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
