<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lc_Keyword</name>
   <tag></tag>
   <elementGuidId>94ffd586-9119-4957-8a8c-f9f2b7e3a6cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Keyword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Keyword&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04867d6b-cea1-471a-a622-a345a90fcac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fc16e27e-06e4-4f2c-8eeb-86b65a3a5307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Keyword</value>
      <webElementGuid>3f1fa797-4cd6-440e-93ba-5b0bf2fdda31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>Keyword</value>
      <webElementGuid>257cc881-23dd-43c8-a9bc-26dd6f58e3e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>ca73cd4f-5a17-4700-b07e-e2337086bb6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập tên sự kiện</value>
      <webElementGuid>88d8ea38-ef06-4e93-9359-0681bfe7e765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_content&quot;)/div[@class=&quot;d-flex flex-column-fluid&quot;]/div[@class=&quot;container-fluid&quot;]/app-content[@class=&quot;management&quot;]/app-event[@class=&quot;component&quot;]/div[@class=&quot;card card-custom gutter-b&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;form form-label-right&quot;]/div[@class=&quot;form-group row ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;col-12 col-md-6 col-lg-6 col-xl-5&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-sm-6 col-md-9 col-xl-9&quot;]/input[@class=&quot;form-control ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>07243ea0-30f8-419d-8e41-8b0dac47014f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Keyword']</value>
      <webElementGuid>f1cb3a2f-a55f-4aa8-b834-059febcd7e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_content']/div/div/app-content/app-event/div/div[2]/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>5ea9f76f-e068-45fb-b43f-4f675a6df899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>02db6c03-c2d3-4cf6-8e64-496ef442f8f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Keyword' and @placeholder = 'Nhập tên sự kiện']</value>
      <webElementGuid>442d7403-414e-47c7-be4d-4919ea925a79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
