<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tn s kin_name</name>
   <tag></tag>
   <elementGuidId>50e56084-8254-4477-bef2-40444b5e3c06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef091e86-3bca-4b74-899c-6b6201eed4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6e60047e-1d09-4f77-9161-0d2e24e57722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>cf53025a-edf9-4792-a6f9-59f190d593c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3431d575-a524-4f4e-a02d-a35a3f1b7092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>0881099c-f12e-4927-bf17-b28544064bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-lg form-control-solid ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>a21bf7ac-0893-4736-a3ee-4ddaba2a9286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tên sự kiện</value>
      <webElementGuid>fc00c110-284d-439d-8bcb-efde93ac355f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_body&quot;)/ngb-modal-window[@class=&quot;d-block modal fade show&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/app-edit-event-modal[@class=&quot;component&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;overlay overlay-block cursor-default modal-body&quot;]/form[@class=&quot;form form-label-right ng-untouched ng-pristine ng-invalid ng-star-inserted&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-lg-9&quot;]/input[@class=&quot;form-control form-control-lg form-control-solid ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>8a18bec5-3eed-40d0-a65a-36b261f8f552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45459a81-bb1b-4ab9-b1ec-89574a884d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c8d7cae4-3664-4763-8eab-21ba83b926d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>86219f30-63eb-443d-8dfe-bbc4b95e10a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8ec227f0-9a35-48b1-a97b-a9d3de4b4f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>c5d293c9-8aa3-44bc-a4aa-03be44ca12d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-lg form-control-solid ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>99234061-f353-4d29-bb56-0e63ad1a2142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tên sự kiện</value>
      <webElementGuid>b247d11e-57e7-46db-964d-986b3b0bc8c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_body&quot;)/ngb-modal-window[@class=&quot;d-block modal fade show&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/app-edit-event-modal[@class=&quot;component&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;overlay overlay-block cursor-default modal-body&quot;]/form[@class=&quot;form form-label-right ng-untouched ng-pristine ng-invalid ng-star-inserted&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-lg-9&quot;]/input[@class=&quot;form-control form-control-lg form-control-solid ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>89cfe2a0-f453-445b-9a7e-28117148ba8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='name']</value>
      <webElementGuid>905d9da6-9f9a-4348-ba4d-e52f49067daa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='kt_body']/ngb-modal-window/div/div/app-edit-event-modal/div/div[2]/form/div/div/input</value>
      <webElementGuid>432b62b3-1e79-4636-bfa3-ef0dd2d83b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>69021482-1218-4c5e-adc3-3baf0f7ed8a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'name' and @placeholder = 'Tên sự kiện']</value>
      <webElementGuid>5de3aa67-931d-4444-8f00-1d81f1a060a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
