<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ngy din ra s kin_ng-tns-c251-5 p-inpu_1a40a5</name>
   <tag></tag>
   <elementGuidId>d181fdd4-3485-42c7-8127-67ca28e189ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ng-tns-c251-5.p-inputtext.p-component.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d7f1612-62c7-4de9-b66d-84a136fa6440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>013aea4b-0cc2-4667-8bec-f063c6a40a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8c80a3bd-57dc-4da2-be50-384264550428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c251-5 p-inputtext p-component ng-star-inserted</value>
      <webElementGuid>802d34cf-d26a-45a8-9198-fb3f7ec2c5a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ngày diễn ra sự kiện</value>
      <webElementGuid>290cff3e-d9c9-44f7-a6e7-8cd2e66e5c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_body&quot;)/ngb-modal-window[@class=&quot;d-block modal fade show&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/app-edit-event-modal[@class=&quot;component&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;overlay overlay-block cursor-default modal-body&quot;]/form[@class=&quot;form form-label-right ng-star-inserted ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-lg-9&quot;]/p-calendar[@class=&quot;ng-tns-c251-5 ng-untouched ng-pristine ng-valid p-inputwrapper-focus&quot;]/span[@class=&quot;ng-tns-c251-5 prime-datetime-picker-override p-calendar p-calendar-w-btn&quot;]/input[@class=&quot;ng-tns-c251-5 p-inputtext p-component ng-star-inserted&quot;]</value>
      <webElementGuid>932ef90c-2ca5-4d19-a441-6febc6e12904</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[8]</value>
      <webElementGuid>d2451bb8-0cc1-41b1-b471-4f1cd2b29f9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='kt_body']/ngb-modal-window/div/div/app-edit-event-modal/div/div[2]/form/div[3]/div/p-calendar/span/input</value>
      <webElementGuid>6f3973e7-94a2-4acc-b1cc-ca7a43a2d7a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/p-calendar/span/input</value>
      <webElementGuid>f09be120-021e-4486-973e-44b39256ad7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Ngày diễn ra sự kiện']</value>
      <webElementGuid>d67708e6-66d8-4226-9ca1-fef929de2dc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
