<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_nbspNovember2022SuMoTuWeThFrSa30311234_74f7e6</name>
   <tag></tag>
   <elementGuidId>0c672544-283b-4c82-843f-89f4424bb212</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='kt_body']/ngb-modal-window/div/div/app-edit-event-modal/div/div[2]/form/div[3]/div/p-calendar/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ng-tns-c251-5.prime-datetime-picker-override.p-calendar.p-calendar-w-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bfbb07a4-5d57-4f05-9f64-0da10d48314d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c251-5 prime-datetime-picker-override p-calendar p-calendar-w-btn</value>
      <webElementGuid>85b83df9-b575-46fb-9a2b-216abdf8fe8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&amp;nbsp;November2022SuMoTuWeThFrSa303112345678910111213141516171819202122232425262728293012314:24</value>
      <webElementGuid>c3b5fa2d-1953-4efb-889a-41208f9e4966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_body&quot;)/ngb-modal-window[@class=&quot;d-block modal fade show&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/app-edit-event-modal[@class=&quot;component&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;overlay overlay-block cursor-default modal-body&quot;]/form[@class=&quot;form form-label-right ng-pristine ng-invalid ng-star-inserted ng-touched&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-lg-9&quot;]/p-calendar[@class=&quot;ng-tns-c251-5 ng-untouched ng-pristine ng-valid p-inputwrapper-focus&quot;]/span[@class=&quot;ng-tns-c251-5 prime-datetime-picker-override p-calendar p-calendar-w-btn&quot;]</value>
      <webElementGuid>869ab989-840f-466d-9e80-299939116a94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='kt_body']/ngb-modal-window/div/div/app-edit-event-modal/div/div[2]/form/div[3]/div/p-calendar/span</value>
      <webElementGuid>2e4208d7-2e05-40c0-a321-32d2c3189e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ngày diễn ra sự kiện'])[2]/following::span[1]</value>
      <webElementGuid>e958e009-83dd-4fb8-a852-24d039c3847e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bắt buộc'])[2]/following::span[1]</value>
      <webElementGuid>0ae1de5d-0a81-426e-94ae-ab15b52d8e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/p-calendar/span</value>
      <webElementGuid>f7f9dd56-6f69-4788-8819-a9e376b370c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '&amp;nbsp;November2022SuMoTuWeThFrSa303112345678910111213141516171819202122232425262728293012314:24' or . = '&amp;nbsp;November2022SuMoTuWeThFrSa303112345678910111213141516171819202122232425262728293012314:24')]</value>
      <webElementGuid>2862c43e-ee94-400a-beb6-21f032b4fc73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
