<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_23</name>
   <tag></tag>
   <elementGuidId>804c2c71-5b76-4a01-bbff-7e3a27d0bf90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='kt_body']/ngb-modal-window/div/div/app-edit-event-modal/div/div[2]/form/div[3]/div/p-calendar/span/div/div/div/div[2]/table/tbody/tr[4]/td[4]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>884103f5-da61-4d03-bba4-6d3953df0752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c60adc3d-c1e5-4fcd-9af0-1a1ae957116e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c251-5 p-ripple ng-star-inserted</value>
      <webElementGuid>ec76d749-3abf-4791-846a-3b39eb7bb35f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>23</value>
      <webElementGuid>a7f6d640-d30d-4265-8d0b-5f7fc461aefb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_body&quot;)/ngb-modal-window[@class=&quot;d-block modal fade show&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/app-edit-event-modal[@class=&quot;component&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;overlay overlay-block cursor-default modal-body&quot;]/form[@class=&quot;form form-label-right ng-star-inserted ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-lg-9&quot;]/p-calendar[@class=&quot;ng-tns-c251-5 ng-pristine ng-valid ng-touched&quot;]/span[@class=&quot;ng-tns-c251-5 prime-datetime-picker-override p-calendar p-calendar-w-btn&quot;]/div[@class=&quot;ng-trigger ng-trigger-overlayAnimation ng-tns-c251-5 p-datepicker p-component ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-group-container ng-tns-c251-5 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-group ng-tns-c251-5 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-calendar-container ng-tns-c251-5 ng-star-inserted&quot;]/table[@class=&quot;p-datepicker-calendar ng-tns-c251-5&quot;]/tbody[@class=&quot;ng-tns-c251-5&quot;]/tr[@class=&quot;ng-tns-c251-5 ng-star-inserted&quot;]/td[@class=&quot;ng-tns-c251-5 ng-star-inserted&quot;]/span[@class=&quot;ng-tns-c251-5 p-ripple ng-star-inserted&quot;]</value>
      <webElementGuid>f144e7ef-5209-4034-b71e-d7e8e935d7f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='kt_body']/ngb-modal-window/div/div/app-edit-event-modal/div/div[2]/form/div[3]/div/p-calendar/span/div/div/div/div[2]/table/tbody/tr[4]/td[4]/span</value>
      <webElementGuid>746e80d9-be8a-4ff6-8a3a-f735638bd7c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[25]</value>
      <webElementGuid>92072af5-5faf-4de3-bed3-1662ca4eadfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::span[26]</value>
      <webElementGuid>849c5f19-669c-4735-81ba-27e3eda9e939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[1]/preceding::span[14]</value>
      <webElementGuid>d1f10395-385c-4020-b3c4-a840c85d0cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hợp lệ'])[3]/preceding::span[18]</value>
      <webElementGuid>d2d4d8c7-c81d-4f12-a7ee-60d77b7b2f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='23']/parent::*</value>
      <webElementGuid>21bd738e-4c16-46d2-b1d4-fcae4738c33c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[4]/span</value>
      <webElementGuid>1c1c9679-6bb4-4029-95da-e41cb01523bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '23' or . = '23')]</value>
      <webElementGuid>710e0b5a-b1e7-4598-9ea4-538cc26b7ffa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
