<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_16</name>
   <tag></tag>
   <elementGuidId>fa66ff6d-9b5b-43b2-ad68-761533fb52a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='kt_body']/ngb-modal-window/div/div/app-edit-event-modal/div/div[2]/form/div[3]/div/p-calendar/span/div/div/div/div[2]/table/tbody/tr[3]/td[4]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e4ba72ab-76ac-4fd8-89a1-0edc3f344b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8ba95226-5dca-4dbe-a860-cd6bc4d390ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c251-7 p-ripple ng-star-inserted</value>
      <webElementGuid>71275f8e-9ccf-4889-a6cb-c32dd36aa8ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>dc5be6a3-8d95-4dd8-95d4-edfed84f40ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_body&quot;)/ngb-modal-window[@class=&quot;d-block modal fade show&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/app-edit-event-modal[@class=&quot;component&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;overlay overlay-block cursor-default modal-body&quot;]/form[@class=&quot;form form-label-right ng-invalid ng-star-inserted ng-dirty ng-touched&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-lg-9&quot;]/p-calendar[@class=&quot;ng-tns-c251-7 ng-pristine ng-valid ng-touched&quot;]/span[@class=&quot;ng-tns-c251-7 prime-datetime-picker-override p-calendar p-calendar-w-btn&quot;]/div[@class=&quot;ng-trigger ng-trigger-overlayAnimation ng-tns-c251-7 p-datepicker p-component ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-group-container ng-tns-c251-7 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-group ng-tns-c251-7 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-calendar-container ng-tns-c251-7 ng-star-inserted&quot;]/table[@class=&quot;p-datepicker-calendar ng-tns-c251-7&quot;]/tbody[@class=&quot;ng-tns-c251-7&quot;]/tr[@class=&quot;ng-tns-c251-7 ng-star-inserted&quot;]/td[@class=&quot;ng-tns-c251-7 ng-star-inserted&quot;]/span[@class=&quot;ng-tns-c251-7 p-ripple ng-star-inserted&quot;]</value>
      <webElementGuid>3f2a27a3-92c1-49d1-9ecb-75dfd71852a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>93464ff6-3034-481a-b69d-c25dda4b16a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>889b526f-9748-4ddb-bfc5-59a9cc2217df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c251-5 p-ripple ng-star-inserted</value>
      <webElementGuid>f867d99f-bbed-481e-a25c-4e4788c67971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>7d6d5dac-3f3b-415d-a4d9-284dbfdd6cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_body&quot;)/ngb-modal-window[@class=&quot;d-block modal fade show&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/app-edit-event-modal[@class=&quot;component&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;overlay overlay-block cursor-default modal-body&quot;]/form[@class=&quot;form form-label-right ng-pristine ng-invalid ng-star-inserted ng-touched&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-lg-9&quot;]/p-calendar[@class=&quot;ng-tns-c251-5 ng-pristine ng-valid ng-touched&quot;]/span[@class=&quot;ng-tns-c251-5 prime-datetime-picker-override p-calendar p-calendar-w-btn&quot;]/div[@class=&quot;ng-trigger ng-trigger-overlayAnimation ng-tns-c251-5 p-datepicker p-component ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-group-container ng-tns-c251-5 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-group ng-tns-c251-5 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-calendar-container ng-tns-c251-5 ng-star-inserted&quot;]/table[@class=&quot;p-datepicker-calendar ng-tns-c251-5&quot;]/tbody[@class=&quot;ng-tns-c251-5&quot;]/tr[@class=&quot;ng-tns-c251-5 ng-star-inserted&quot;]/td[@class=&quot;ng-tns-c251-5 ng-star-inserted&quot;]/span[@class=&quot;ng-tns-c251-5 p-ripple ng-star-inserted&quot;]</value>
      <webElementGuid>3cc1e992-76ef-4ae0-bf97-fdbeeebad7d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='kt_body']/ngb-modal-window/div/div/app-edit-event-modal/div/div[2]/form/div[3]/div/p-calendar/span/div/div/div/div[2]/table/tbody/tr[3]/td[4]/span</value>
      <webElementGuid>16b604cd-4ffd-433e-a831-10e1a50b4350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[18]</value>
      <webElementGuid>418829ba-6ea6-4549-83a6-a86fdcde8652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::span[19]</value>
      <webElementGuid>4f7e37d9-3ca3-4c03-86fd-b2dd98acfbf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[1]/preceding::span[21]</value>
      <webElementGuid>f883ed83-1b79-4e5b-a20f-edf63491635c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hợp lệ'])[2]/preceding::span[25]</value>
      <webElementGuid>aa4ab4bf-3c2d-4668-b616-7fdd8d5428f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='16']/parent::*</value>
      <webElementGuid>5109a68e-f43d-4c90-ac8f-9f6d3d51b54f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/span</value>
      <webElementGuid>b913c6c3-3369-4639-b342-acd739590da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '16' or . = '16')]</value>
      <webElementGuid>b927d5aa-60c7-4ae8-9d54-bcc5c84b4102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hợp lệ'])[1]/preceding::span[25]</value>
      <webElementGuid>7bc6f023-e21a-4196-a828-20a018f2e733</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
