<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>app-paginator_1 (current)</name>
   <tag></tag>
   <elementGuidId>67107e64-af37-4938-b21f-206e5abcf84d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='p-tabpanel-0']/app-paginator</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>app-paginator.d-flex.justify-content-between.align-items-center.flex-wrap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>app-paginator</value>
      <webElementGuid>35511b38-aac4-47a4-bab8-aeed69245cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex justify-content-between align-items-center flex-wrap</value>
      <webElementGuid>9e835a39-7c77-4dd4-8d0c-41f9b856cbad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 1 (current)</value>
      <webElementGuid>bd795b61-28a1-4988-9eb3-36b607ccc47e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-0&quot;)/app-paginator[@class=&quot;d-flex justify-content-between align-items-center flex-wrap&quot;]</value>
      <webElementGuid>96b8eff4-09e5-4bdf-8b29-0098671bdfe0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p-tabpanel-0']/app-paginator</value>
      <webElementGuid>f3566f4b-d2bf-4e2a-93cf-b4881f77cef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trang chủ'])[3]/following::app-paginator[1]</value>
      <webElementGuid>562ab632-220a-4d9c-a9af-aac39de91d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trang chủ'])[2]/following::app-paginator[1]</value>
      <webElementGuid>e4e89863-d64c-4555-af6d-62e4e9753c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STT'])[2]/preceding::app-paginator[1]</value>
      <webElementGuid>47b29e10-7f31-428e-9269-468b0beca8de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-paginator</value>
      <webElementGuid>d74c34d5-0c38-47f7-830d-4707039d1c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//app-paginator[(text() = ' 1 (current)' or . = ' 1 (current)')]</value>
      <webElementGuid>a471ca59-902e-4dde-b40b-ce76ce24de4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
