<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Qun tr ni dung  Qun l menu Danh sch men_beff1c</name>
   <tag></tag>
   <elementGuidId>e7c4b602-f682-4bd5-8f91-e2830c186cab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kt_content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6bc5c755-1b26-4722-8695-f612762f0db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kt_content</value>
      <webElementGuid>58c417a0-bf26-4522-b274-5ef7d0cf1dda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content d-flex flex-column flex-column-fluid</value>
      <webElementGuid>f3077e98-b5e8-4ceb-8bc5-f9255bded894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Quản trị nội dung  Quản lý menu Danh sách menuThêm mớiLọcTìm kiếmAdmin PortalIoCSTT Tên menu  Mô tả Thao tác1 Cấu hình SSO Cấu hình SSO2 Quản lý QR Code QR Code3 Quản trị thư mục, báo cáo Quản trị thư mục, báo cáo4 Quản trị hệ thống Quản trị hệ thống5 Quản trị nội dung Quản trị nội dung6 Trang chủ Trang chủ 1 (current)STT Tên menu  Mô tả  Trạng thái Thao tác1 Cấu hình SSO Cấu hình SSOHiển thị2 Quản lý QR Code QR CodeHiển thị3 Quản trị thư mục, báo cáo Quản trị thư mục, báo cáoHiển thị4 Quản trị hệ thống Quản trị hệ thốngHiển thị5 Quản trị nội dung Quản trị nội dungHiển thị6 Trang chủ Trang chủHiển thị 1 (current)</value>
      <webElementGuid>02ddb582-854f-4f2d-ad44-4332a699a1ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_content&quot;)</value>
      <webElementGuid>81b14884-bebf-4aa2-9f61-3032ab7e62da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='kt_content']</value>
      <webElementGuid>9f629ada-d009-4b5c-8037-80e0f08f9a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_wrapper']/div</value>
      <webElementGuid>70cecb21-e0a3-4323-9515-0daf8eb27b6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='l'])[1]/following::div[1]</value>
      <webElementGuid>77d3798f-65db-4a48-a8df-30b0107675e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='lcloi7805'])[1]/following::div[1]</value>
      <webElementGuid>0a6969d7-7eb2-46b1-81ee-89643b1b4787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div</value>
      <webElementGuid>2060b5e3-6ddb-4b41-86ce-552d1df8c1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'kt_content' and (text() = ' Quản trị nội dung  Quản lý menu Danh sách menuThêm mớiLọcTìm kiếmAdmin PortalIoCSTT Tên menu  Mô tả Thao tác1 Cấu hình SSO Cấu hình SSO2 Quản lý QR Code QR Code3 Quản trị thư mục, báo cáo Quản trị thư mục, báo cáo4 Quản trị hệ thống Quản trị hệ thống5 Quản trị nội dung Quản trị nội dung6 Trang chủ Trang chủ 1 (current)STT Tên menu  Mô tả  Trạng thái Thao tác1 Cấu hình SSO Cấu hình SSOHiển thị2 Quản lý QR Code QR CodeHiển thị3 Quản trị thư mục, báo cáo Quản trị thư mục, báo cáoHiển thị4 Quản trị hệ thống Quản trị hệ thốngHiển thị5 Quản trị nội dung Quản trị nội dungHiển thị6 Trang chủ Trang chủHiển thị 1 (current)' or . = ' Quản trị nội dung  Quản lý menu Danh sách menuThêm mớiLọcTìm kiếmAdmin PortalIoCSTT Tên menu  Mô tả Thao tác1 Cấu hình SSO Cấu hình SSO2 Quản lý QR Code QR Code3 Quản trị thư mục, báo cáo Quản trị thư mục, báo cáo4 Quản trị hệ thống Quản trị hệ thống5 Quản trị nội dung Quản trị nội dung6 Trang chủ Trang chủ 1 (current)STT Tên menu  Mô tả  Trạng thái Thao tác1 Cấu hình SSO Cấu hình SSOHiển thị2 Quản lý QR Code QR CodeHiển thị3 Quản trị thư mục, báo cáo Quản trị thư mục, báo cáoHiển thị4 Quản trị hệ thống Quản trị hệ thốngHiển thị5 Quản trị nội dung Quản trị nội dungHiển thị6 Trang chủ Trang chủHiển thị 1 (current)')]</value>
      <webElementGuid>d867e9d2-147d-420a-8341-72b0e5238fe3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
