<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Thng bo</name>
   <tag></tag>
   <elementGuidId>fd4e5a78-c6d9-4a2e-8f51-a3b51451b221</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='kt_body']/ngb-modal-window/div/div/app-edit-menu-management-modal/div/div[2]/form/div[3]/div/p-dropdown/div/div[3]/div[2]/ul/p-dropdownitem[2]/li/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ea32e364-6424-4051-9351-d3f843964030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>75b61fdb-7086-43dc-a53a-1112f86ff983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thông báo</value>
      <webElementGuid>cfdf20ae-4893-47e9-bb4e-d717932bbefa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_body&quot;)/ngb-modal-window[@class=&quot;d-block modal fade show&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/app-edit-menu-management-modal[1]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;overlay overlay-block cursor-default modal-body&quot;]/form[@class=&quot;form form-label-right ng-invalid ng-star-inserted ng-dirty ng-touched&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-lg-9&quot;]/p-dropdown[@class=&quot;ng-tns-c244-2 ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;ng-tns-c244-2 p-dropdown p-component p-dropdown-open p-dropdown-clearable&quot;]/div[@class=&quot;ng-trigger ng-trigger-overlayAnimation ng-tns-c244-2 p-dropdown-panel p-component ng-star-inserted&quot;]/div[@class=&quot;p-dropdown-items-wrapper ng-tns-c244-2&quot;]/ul[@class=&quot;p-dropdown-items ng-tns-c244-2&quot;]/p-dropdownitem[@class=&quot;ng-tns-c244-2 ng-star-inserted&quot;]/li[@class=&quot;p-dropdown-item p-ripple&quot;]/span[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>8b123ede-6938-427b-84f3-e85e4f031146</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='kt_body']/ngb-modal-window/div/div/app-edit-menu-management-modal/div/div[2]/form/div[3]/div/p-dropdown/div/div[3]/div[2]/ul/p-dropdownitem[2]/li/span</value>
      <webElementGuid>f515b236-db18-4e7c-a50d-c90e75598645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thông báo'])[1]/following::span[1]</value>
      <webElementGuid>b4bc18be-d364-4f3f-b983-66602c9eae79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu cha'])[2]/following::span[4]</value>
      <webElementGuid>e13f457a-fb9f-4cca-96ba-70fd13ad5241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Khen thưởng học sinh'])[1]/preceding::span[1]</value>
      <webElementGuid>c4b7b14e-bf77-43a3-ab65-f0bdc1ef5c01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xếp loại năng lực, phẩm chất'])[1]/preceding::span[2]</value>
      <webElementGuid>6814870b-3c15-4afb-9ae8-5cf4d5da5101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-dropdownitem[2]/li/span</value>
      <webElementGuid>b3c0ca21-a465-42e1-a2ea-d2df56e782fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Thông báo' or . = 'Thông báo')]</value>
      <webElementGuid>76888572-8ad1-4590-8f71-7220dba62026</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
