<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tn loi d liu_name</name>
   <tag></tag>
   <elementGuidId>47be14f3-9a1f-4430-beb8-d23163446e73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5aa7a7ad-5c6a-4e52-ad4c-149d1c0cc665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8a8e7e9e-5f7e-44b2-9409-6e1f0189ec26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>316bc8f7-554c-4665-8c98-96f249909b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập tên loại dữ liệu</value>
      <webElementGuid>410c2e22-50bb-4e96-8f29-a68e19d01891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ef7bd18e-354c-49b7-8ae7-312f6306bc16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>ea13c40c-2830-4152-9601-6890c5f63f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-lg form-control-solid ng-untouched is-valid ng-dirty ng-valid</value>
      <webElementGuid>47c6dc68-2907-4854-9229-9956bbfaa945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>3ccb9811-42e1-4b62-ab8f-37e768f77797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_body&quot;)/ngb-modal-window[@class=&quot;d-block modal fade show&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/app-edit-data-mining-source[1]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;overlay overlay-block cursor-default modal-body&quot;]/form[@class=&quot;form form-label-right ng-untouched ng-invalid ng-star-inserted ng-dirty&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-lg-9&quot;]/input[@class=&quot;form-control form-control-lg form-control-solid ng-untouched is-valid ng-dirty ng-valid&quot;]</value>
      <webElementGuid>de23d194-6c3a-4bc9-a7c5-3220e0004d0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='name']</value>
      <webElementGuid>3a451c87-608a-4816-abfc-0f3db5c764f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='kt_body']/ngb-modal-window/div/div/app-edit-data-mining-source/div/div[2]/form/div/div/input</value>
      <webElementGuid>0b6c9e52-d7a9-4e7a-9316-1a1d4ccff081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>4839564e-d625-4990-88f4-7c79073787e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'name' and @placeholder = 'Nhập tên loại dữ liệu']</value>
      <webElementGuid>d5f352a8-d0ff-4934-9161-7a7840b80fe9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
