<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Hin th_btn btn-icon btn-sm btn-light btn-_1f1b4e</name>
   <tag></tag>
   <elementGuidId>a0e74ba0-ec90-479b-bf6c-35c9e2dd489c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_content']/div/div/app-content/app-widget-management/div/div[2]/app-paginator/div[2]/ng-pagination/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3d7fcfa8-e46e-4196-aa48-d0e3d64fe2c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Previous</value>
      <webElementGuid>3ef31193-ca38-4275-9f9d-06d955a8c047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-icon btn-sm btn-light btn-hover-primary mr-2 my-1</value>
      <webElementGuid>0dc23e29-d79a-40ca-8702-ad003f50ae22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_content&quot;)/div[@class=&quot;d-flex flex-column-fluid&quot;]/div[@class=&quot;container-fluid&quot;]/app-content[@class=&quot;management&quot;]/app-widget-management[1]/div[@class=&quot;card card-custom gutter-b&quot;]/div[@class=&quot;card-body&quot;]/app-paginator[@class=&quot;d-flex justify-content-between align-items-center flex-wrap&quot;]/div[@class=&quot;d-flex align-items-center py-3&quot;]/ng-pagination[1]/a[@class=&quot;btn btn-icon btn-sm btn-light btn-hover-primary mr-2 my-1&quot;]</value>
      <webElementGuid>f7b5eba7-a05e-4681-89b2-9c0b08e66b7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_content']/div/div/app-content/app-widget-management/div/div[2]/app-paginator/div[2]/ng-pagination/a[2]</value>
      <webElementGuid>2a0fa1d6-af30-4494-81b7-35bb4550ee8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hiển thị'])[1]/following::a[4]</value>
      <webElementGuid>2330118f-1cb8-4282-876f-f37efddc185a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Báo cáo'])[2]/following::a[4]</value>
      <webElementGuid>207e67aa-7cd0-46a8-bd59-db4085441dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(current)'])[1]/preceding::a[2]</value>
      <webElementGuid>a76130a0-7aac-448f-8ca3-6d22df7a3d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Audit Logs'])[1]/preceding::a[5]</value>
      <webElementGuid>7906c042-bc59-4549-b6f2-85a0b504c14c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[31]</value>
      <webElementGuid>399239bc-5bbe-4808-ab43-65d30015d8d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-pagination/a[2]</value>
      <webElementGuid>2202ddde-9338-46d1-9dcd-92f4ed385091</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
