<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_nbspNovember2022SuMoTuWeThFrSa30311234_5ec700</name>
   <tag></tag>
   <elementGuidId>5568168e-90d2-4530-801c-d9cc7984cb57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='kt_body']/ngb-modal-window/div/div/app-edit-event-modal/div/div[2]/form/div[3]/div/p-calendar/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ng-tns-c251-5.prime-datetime-picker-override.p-calendar.p-calendar-w-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bf46aa1e-cd0c-4506-aa2a-ed4bb8afcb88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c251-5 prime-datetime-picker-override p-calendar p-calendar-w-btn</value>
      <webElementGuid>8b8b3f1a-4df1-4139-830a-d0f49779a82f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&amp;nbsp;November2022SuMoTuWeThFrSa303112345678910111213141516171819202122232425262728293012314:12</value>
      <webElementGuid>63259005-cbf3-43f4-b1ce-60efd3b630cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_body&quot;)/ngb-modal-window[@class=&quot;d-block modal fade show&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/app-edit-event-modal[@class=&quot;component&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;overlay overlay-block cursor-default modal-body&quot;]/form[@class=&quot;form form-label-right ng-star-inserted ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-lg-9&quot;]/p-calendar[@class=&quot;ng-tns-c251-5 ng-untouched ng-pristine ng-valid p-inputwrapper-focus&quot;]/span[@class=&quot;ng-tns-c251-5 prime-datetime-picker-override p-calendar p-calendar-w-btn&quot;]</value>
      <webElementGuid>afd0a1a6-6f76-469d-939c-27fb53abadf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='kt_body']/ngb-modal-window/div/div/app-edit-event-modal/div/div[2]/form/div[3]/div/p-calendar/span</value>
      <webElementGuid>e7c60428-6021-4b37-b941-6d48a9dcd304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ngày diễn ra sự kiện'])[2]/following::span[1]</value>
      <webElementGuid>6ade2727-b89a-46d2-a632-278006a4b0bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hợp lệ'])[2]/following::span[1]</value>
      <webElementGuid>a4ccd4d2-6110-4fe0-bdda-45e8a74ef9b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/p-calendar/span</value>
      <webElementGuid>c7dc47b5-7eea-4f67-a736-ef020b4fe58f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '&amp;nbsp;November2022SuMoTuWeThFrSa303112345678910111213141516171819202122232425262728293012314:12' or . = '&amp;nbsp;November2022SuMoTuWeThFrSa303112345678910111213141516171819202122232425262728293012314:12')]</value>
      <webElementGuid>f3d85106-4aa9-420a-a335-bfcfb2442d7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
