<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_15</name>
   <tag></tag>
   <elementGuidId>872f53e2-2d26-4b7e-9634-c6d1f50edc17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='kt_body']/ngb-modal-window/div/div/app-edit-event-modal/div/div[2]/form/div[3]/div/p-calendar/span/div/div/div/div[2]/table/tbody/tr[3]/td[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>452ac8bb-6cd8-4a1c-ba0c-bb7967cf9300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5a65428b-45e2-43a6-91a5-56a374bc7b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c251-5 p-ripple ng-star-inserted</value>
      <webElementGuid>1090d229-3ecc-4ac5-ab5f-f4a85737c97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>a0d1de76-7049-4f00-83a7-433a472ebd8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_body&quot;)/ngb-modal-window[@class=&quot;d-block modal fade show&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/app-edit-event-modal[@class=&quot;component&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;overlay overlay-block cursor-default modal-body&quot;]/form[@class=&quot;form form-label-right ng-star-inserted ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-lg-9&quot;]/p-calendar[@class=&quot;ng-tns-c251-5 ng-pristine ng-valid ng-touched&quot;]/span[@class=&quot;ng-tns-c251-5 prime-datetime-picker-override p-calendar p-calendar-w-btn&quot;]/div[@class=&quot;ng-trigger ng-trigger-overlayAnimation ng-tns-c251-5 p-datepicker p-component ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-group-container ng-tns-c251-5 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-group ng-tns-c251-5 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-calendar-container ng-tns-c251-5 ng-star-inserted&quot;]/table[@class=&quot;p-datepicker-calendar ng-tns-c251-5&quot;]/tbody[@class=&quot;ng-tns-c251-5&quot;]/tr[@class=&quot;ng-tns-c251-5 ng-star-inserted&quot;]/td[@class=&quot;ng-tns-c251-5 ng-star-inserted&quot;]/span[@class=&quot;ng-tns-c251-5 p-ripple ng-star-inserted&quot;]</value>
      <webElementGuid>987ef15e-e9c1-4641-869e-f415850abfea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='kt_body']/ngb-modal-window/div/div/app-edit-event-modal/div/div[2]/form/div[3]/div/p-calendar/span/div/div/div/div[2]/table/tbody/tr[3]/td[3]/span</value>
      <webElementGuid>c7ec9a27-cc9a-46e0-8240-14630383d389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[17]</value>
      <webElementGuid>1c0a55a0-da7f-478f-be7d-64795edb6c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::span[18]</value>
      <webElementGuid>31a40d23-9300-4d08-b486-e68bd1098578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[1]/preceding::span[22]</value>
      <webElementGuid>169c7e73-42ba-487e-804a-90c685960bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hợp lệ'])[3]/preceding::span[26]</value>
      <webElementGuid>1742c838-fe62-45e2-9696-e71924758c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='15']/parent::*</value>
      <webElementGuid>f3af33da-bdad-4924-bec9-8187f0b2c2d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/span</value>
      <webElementGuid>caf2ebfb-933a-42eb-862d-14031979aab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '15' or . = '15')]</value>
      <webElementGuid>9e8747aa-8eb8-4b75-8acd-e5324dd4c80a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
