<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_l</name>
   <tag></tag>
   <elementGuidId>12b9d4cb-62b4-4790-887c-66186130c28d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_quick_user_toggle']/span[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.symbol-label.font-size-h5.font-weight-bold</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>95acc755-ab13-40f2-89c8-da52030bd109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>symbol-label font-size-h5 font-weight-bold</value>
      <webElementGuid>cfb5f600-88ac-4162-9bc7-08ec8fa706e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>l</value>
      <webElementGuid>4805bd58-0b64-4175-a9ae-117c1f7a7427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_quick_user_toggle&quot;)/span[@class=&quot;symbol symbol-lg-35 symbol-25 symbol-light-success&quot;]/span[@class=&quot;symbol-label font-size-h5 font-weight-bold&quot;]</value>
      <webElementGuid>228b5db4-8bd1-4fd8-9420-16bffb42e56e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_quick_user_toggle']/span[3]/span</value>
      <webElementGuid>35b327fd-47b0-4360-8e1e-b59bb1214d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='lcloi7805'])[1]/following::span[2]</value>
      <webElementGuid>30e1f405-b19c-4f36-babe-86ed768b7884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xin chào,'])[1]/following::span[3]</value>
      <webElementGuid>0790f46a-77a0-4d5b-b5fd-0f5462664e02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Widget'])[1]/preceding::span[1]</value>
      <webElementGuid>a09333ba-f6ca-4c22-9679-f58e955ec9a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm widget'])[1]/preceding::span[1]</value>
      <webElementGuid>df4534c9-c39d-4d32-84c9-30fa872e225a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='l']/parent::*</value>
      <webElementGuid>a6b2717e-a2d2-4cc8-8644-373698491649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/span</value>
      <webElementGuid>d95a85e3-007c-472c-83a6-1649ee0ba8c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'l' or . = 'l')]</value>
      <webElementGuid>bfbec2a3-c00e-4fea-bf3c-4bd2132f92ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
