<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Qun l ng b lnh vc th tc hnh chnh</name>
   <tag></tag>
   <elementGuidId>8ef0e106-4877-45ed-8fa5-59949a30bd87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_aside_menu']/ul/li[2]/div/ul/li[3]/div/ul/li[3]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fe0e2926-ebfe-4af8-bcdb-8dae0fd3a807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-text</value>
      <webElementGuid>dbc0256d-5262-4ec6-a672-5f2edf516d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-translate</name>
      <type>Main</type>
      <value>Quản lý đồng bộ lĩnh vực thủ t</value>
      <webElementGuid>60fc6415-0c29-4d3c-a71a-76ec8873ec4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Quản lý đồng bộ lĩnh vực thủ tục hành chính</value>
      <webElementGuid>4559e620-59fd-4cbb-9505-f74f84556201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_aside_menu&quot;)/ul[@class=&quot;menu-nav&quot;]/li[@class=&quot;menu-item menu-item-submenu menu-item-open&quot;]/div[@class=&quot;menu-submenu&quot;]/ul[@class=&quot;menu-subnav&quot;]/li[@class=&quot;menu-item menu-item-submenu menu-item-open&quot;]/div[@class=&quot;menu-submenu&quot;]/ul[@class=&quot;menu-subnav&quot;]/li[@class=&quot;menu-item&quot;]/a[@class=&quot;menu-link&quot;]/span[@class=&quot;menu-text&quot;]</value>
      <webElementGuid>1da050f1-49c1-4df9-88b2-56784c16aa4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_aside_menu']/ul/li[2]/div/ul/li[3]/div/ul/li[3]/a/span</value>
      <webElementGuid>78ab7a64-cccb-4f9e-8b84-877c449413c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quản lý danh mục nguồn dữ liệu'])[1]/following::span[2]</value>
      <webElementGuid>b6566a6a-c66c-43f3-ad90-c6e1a9e38328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quản lý danh mục nguồn khai thác'])[1]/following::span[4]</value>
      <webElementGuid>fa760087-b7c5-4f39-bb9b-e1deecb7de73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quản lý đồng bộ thủ tục hành chính'])[1]/preceding::span[2]</value>
      <webElementGuid>c520f483-c546-43b5-8de3-b54152d9cab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quản lý thông tin kết quả thủ tục hành chính'])[1]/preceding::span[4]</value>
      <webElementGuid>d0951e03-981b-4660-aa9d-bbedfa3a56bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Quản lý đồng bộ lĩnh vực thủ tục hành chính']/parent::*</value>
      <webElementGuid>2486605e-3407-4236-8c7b-f0f54e972682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/ul/li[3]/div/ul/li[3]/a/span</value>
      <webElementGuid>d293d8e1-b2d3-4029-a179-45db16e512c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Quản lý đồng bộ lĩnh vực thủ tục hành chính' or . = 'Quản lý đồng bộ lĩnh vực thủ tục hành chính')]</value>
      <webElementGuid>a8d303a7-7e45-4640-8124-765ef454498b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
