<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Qun l danh mc hnh thc cung cp</name>
   <tag></tag>
   <elementGuidId>49ace0e7-ed36-4e83-b759-7322e1e54d51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_aside_menu']/ul/li[2]/div/ul/li[2]/div/ul/li[4]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e9bbbb15-859d-4c8e-8df2-4d1f9e56de4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-text</value>
      <webElementGuid>4cf46c6e-6fbd-4cb6-8eb1-05bebefaccc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-translate</name>
      <type>Main</type>
      <value> Quản lý danh mục hình thức cu</value>
      <webElementGuid>397545ff-7109-4193-8cb3-e6bc611ae0ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Quản lý danh mục hình thức cung cấp</value>
      <webElementGuid>fd07574d-3f3d-47fd-ae62-e5df43599d7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_aside_menu&quot;)/ul[@class=&quot;menu-nav&quot;]/li[@class=&quot;menu-item menu-item-submenu menu-item-open&quot;]/div[@class=&quot;menu-submenu&quot;]/ul[@class=&quot;menu-subnav&quot;]/li[@class=&quot;menu-item menu-item-submenu menu-item-open&quot;]/div[@class=&quot;menu-submenu&quot;]/ul[@class=&quot;menu-subnav&quot;]/li[@class=&quot;menu-item&quot;]/a[@class=&quot;menu-link&quot;]/span[@class=&quot;menu-text&quot;]</value>
      <webElementGuid>70d96ae1-9305-41f5-b420-b64940f52a70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_aside_menu']/ul/li[2]/div/ul/li[2]/div/ul/li[4]/a/span</value>
      <webElementGuid>5bbe4be4-61f5-44a4-9224-e1b0d8a1bb26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quản lý danh mục lĩnh vực'])[1]/following::span[2]</value>
      <webElementGuid>1e840f7d-bb4f-4bfc-af11-60af5f2b8387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quản lý danh mục loại dữ liệu'])[1]/following::span[4]</value>
      <webElementGuid>0c4cb7c7-48ea-4d5e-b6e7-6bc816045380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Danh mục thủ tục hành chính'])[1]/preceding::span[2]</value>
      <webElementGuid>d2c7b0a1-79d7-4ef8-8004-1a7b7e4971fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quản lý danh mục nguồn khai thác'])[1]/preceding::span[4]</value>
      <webElementGuid>361e69d1-cf3a-42dd-b875-278b493af0b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Quản lý danh mục hình thức cung cấp']/parent::*</value>
      <webElementGuid>a297db73-eaea-4b54-93d2-d6304380d1ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/span</value>
      <webElementGuid>5202f45c-594c-41c2-b782-1b701e52e224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Quản lý danh mục hình thức cung cấp' or . = ' Quản lý danh mục hình thức cung cấp')]</value>
      <webElementGuid>2e3dede8-4434-4a01-aa1e-fa754e95517e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
