<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Qun l danh mc n v cung cp d liu</name>
   <tag></tag>
   <elementGuidId>2f1e55df-f291-4d15-9224-ac6cc31837e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_content']/div/div/app-data-catalog/app-data-provider-management/div/div/div/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3.card-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>57a21547-f127-466f-85ce-60e47ca8f207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-label</value>
      <webElementGuid>2b82224c-29e9-4a78-ad74-b0f1356e6c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Quản lý danh mục đơn vị cung cấp dữ liệu</value>
      <webElementGuid>033e1357-13d9-417b-b78a-5acd35cd4d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_content&quot;)/div[@class=&quot;d-flex flex-column-fluid&quot;]/div[@class=&quot;container-fluid&quot;]/app-data-catalog[1]/app-data-provider-management[1]/div[@class=&quot;card card-custom gutter-b&quot;]/div[@class=&quot;card-header&quot;]/div[@class=&quot;card-title&quot;]/h3[@class=&quot;card-label&quot;]</value>
      <webElementGuid>72664955-b609-495b-b475-9e1c11f6ea1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_content']/div/div/app-data-catalog/app-data-provider-management/div/div/div/h3</value>
      <webElementGuid>828fdf20-a570-4378-ab6b-1062806c8ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thống kê duyệt dữ liệu'])[1]/following::h3[1]</value>
      <webElementGuid>46fcc90d-52d6-4781-bab0-07f407a2eddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quản lý dữ liệu theo trạng thái'])[1]/following::h3[1]</value>
      <webElementGuid>c79e7b75-2c3c-44b0-8210-a1de507057a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm mới'])[1]/preceding::h3[1]</value>
      <webElementGuid>476cc805-13dc-4202-be37-d64a52c71d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lọc'])[1]/preceding::h3[1]</value>
      <webElementGuid>794d7dfe-360d-4606-8ef4-58012d2453fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Quản lý danh mục đơn vị cung cấp dữ liệu']/parent::*</value>
      <webElementGuid>1544d1a1-e017-4300-ad4b-ee18436a2a10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>10651608-6ec7-4db0-ab8c-c052de99519a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Quản lý danh mục đơn vị cung cấp dữ liệu' or . = 'Quản lý danh mục đơn vị cung cấp dữ liệu')]</value>
      <webElementGuid>423927ae-d8dd-48f1-9a6e-40103447ca6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
