<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtVerify</name>
   <tag></tag>
   <elementGuidId>442c4e18-d41f-4119-ba49-517ad165050d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;kt_content&quot;]/div/div/app-categories/app-data-catalog/app-data-provider-management/div/div[2]/p-table/div/div/table/tbody/tr[1]/td[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
